<?xml version="1.0" encoding="UTF-8" ?>
<testsuites name="vitest tests" tests="3" failures="1" errors="0" time="3.121">
    <testsuite name="tests/challenge0.test.js" timestamp="2024-01-04T10:40:34.500Z" hostname="LAPTOP-OMBJIULC" tests="3" failures="1" errors="0" skipped="0" time="1.66">
        <testcase classname="tests/challenge0.test.js" name="Pre authentication tasks &gt; Challenge 0.a - User not found do not expose too much information" time="0.393">
        </testcase>
        <testcase classname="tests/challenge0.test.js" name="Pre authentication tasks &gt; Challenge 0.b - Wrong password do not expose too much information" time="0.42">
        </testcase>
        <testcase classname="tests/challenge0.test.js" name="Post authentication tasks &gt; Challenge 0.c - Show user&apos;s firstname and lastname in welcome message" time="0.367">
            <failure message="expected { id: 1, …(5) } to have property &quot;firstname&quot;" type="AssertionError">
AssertionError: expected { id: 1, …(5) } to have property &quot;firstname&quot;
 ❯ tests/challenge0.test.js:72:26
            </failure>
        </testcase>
    </testsuite>
</testsuites>
